spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${DB_URL}
    username: todaysentence
    password: ${DB_PASSWORD}
    hikari:
      minimum-idle: 2
      maximum-pool-size: 5
      connection-timeout: 5000
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-test-query: SELECT 1

  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MariaDB103Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: DEBUG  # Hibernate SQL 로깅 활성화
    org.hibernate.type.descriptor.sql: TRACE  # 파라미터 바인딩 로깅 활성화

server:
  port: 8080
