server:
  port: 8080  # 로컬 서버 포트 설정

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/today
    username: root
    password: "0000"
  mail:
    host: smtp.gmail.com
    port: 587
    username: "mical0108@gmail.com"
    password: "zjqb opgn ijti fnjd"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
        debug: true
  data:
    redis:
      host: localhost
      port: 6379

  jpa:
    hibernate:
      ddl-auto: update  # DB 스키마 자동 생성 (개발 환경에서만 사용)
    show-sql: true  # SQL 쿼리 출력
    properties:
      hibernate:
        format_sql: false

  h2:
    console:
      enabled: true  # H2 콘솔 활성화
      path: /h2-console  # H2 콘솔 접속 경로

jwt:
  secret:
    key: "7Jik64qY7J2Y66qF7Ja4Snd07YKk6rCS7J2E7KCV7ZW067O07J6Q"

logging:
  level:
    root: info
