
  data:
    redis:
      host: redis
      port: 6379

  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MariaDB103Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    root: DEBUG
    org.hibernate.SQL: DEBUG  # Hibernate SQL 로깅 활성화
    org.hibernate.type.descriptor.sql: TRACE  # 파라미터 바인딩 로깅 활성화



server:
  port: 8080
